#!/bin/bash

## gcloud
alias gcl='gcloud'
gclc() {
	if [[ $# -eq 0 ]]; then
		gcl config configurations list
	else
		gcl config configurations activate $@
	fi
}

## kubectl
alias kc='kubectl'
source <(kubectl completion bash)
complete -o default -F __start_kubectl kc

alias kck='kc kustomize'

kcc() {
	if [[ $# -eq 0 ]]; then
		kc config get-contexts
	else
		kc config use-context $@
	fi
}

gcc() {
	if [[ $# -eq 0 ]]; then
		export KUBECONFIG=$HOME/.kube/config-personal
		gcl config configurations activate rnd
	else
		export KUBECONFIG=$HOME/.kube/config-$@
		gcl config configurations activate $@
	fi
}

# apps
alias dc="docker-compose"
alias gldoc="godoc -http=:6060"

## tools
alias l="ls -la"
alias d="kitty +kitten diff"

## directories
alias dot="cd $HOME/dotfiles"
