#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=2000

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/randy/google-cloud-sdk/path.bash.inc' ]; then . '/home/randy/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/randy/google-cloud-sdk/completion.bash.inc' ]; then . '/home/randy/google-cloud-sdk/completion.bash.inc'; fi

[[ -f ~/.extend.bashrc ]] &&  . ~/.extend.bashrc                    
