set encoding=utf-8

syntax off
filetype plugin indent on

set ruler smartindent
set synmaxcol=240
set wrap linebreak nolist nojoinspaces
set nobackup noswapfile nowritebackup
set noexpandtab tabstop=8 softtabstop=8 shiftwidth=8
set textwidth=80 formatoptions-=t formatoptions+=j
set showcmd showmode hidden
set magic matchtime=2 lazyredraw
set incsearch ignorecase smartcase showmatch hlsearch
set autoread laststatus=2
