execute pathogen#infect()
syntax on
filetype plugin indent on

""""""""""""""""""""""""""""""""""""""""""""""""'
" UI configuration
"""""""""""""""""""""""""""""""""""""""""""""""""
set tw=80
set nu
set ts=4
set sts=4
set sw=4
set et
