#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# Start X server
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

# Register dotfiles
dotfiles=(
    aliases
    bash_prompt
    exports
)

# Load dotfiles 
for file in "${dotfiles[@]}"; do
    [ -r "$HOME/.$file" ] && source $HOME/.$file
done
unset file

# History file config
HISTSIZE=1000
HISTFILESIZE=2000

